
package ch03.image.client2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SkiImageService", targetNamespace = "http://image.ch03/", wsdlLocation = "file:/C:/Users/jaime/Desktop/SCDJWS/ch02/wsimportproject/ch03/image/image.wsdl")
public class SkiImageService_Service
    extends Service
{

    private final static URL SKIIMAGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ch03.image.client2.SkiImageService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ch03.image.client2.SkiImageService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/jaime/Desktop/SCDJWS/ch02/wsimportproject/ch03/image/image.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/jaime/Desktop/SCDJWS/ch02/wsimportproject/ch03/image/image.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SKIIMAGESERVICE_WSDL_LOCATION = url;
    }

    public SkiImageService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SkiImageService_Service() {
        super(SKIIMAGESERVICE_WSDL_LOCATION, new QName("http://image.ch03/", "SkiImageService"));
    }

    /**
     * 
     * @return
     *     returns SkiImageService
     */
    @WebEndpoint(name = "SkiImageServicePort")
    public SkiImageService getSkiImageServicePort() {
        return super.getPort(new QName("http://image.ch03/", "SkiImageServicePort"), SkiImageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SkiImageService
     */
    @WebEndpoint(name = "SkiImageServicePort")
    public SkiImageService getSkiImageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://image.ch03/", "SkiImageServicePort"), SkiImageService.class, features);
    }

}
