
package clienta;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AnnotatedTimeServer", targetNamespace = "http://ch02.tsa")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnnotatedTimeServer {


    /**
     * 
     * @param clientMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "time_string")
    @WebResult(name = "ts_out", targetNamespace = "http://ch02.tsa")
    @RequestWrapper(localName = "time_string", targetNamespace = "http://ch02.tsa", className = "clienta.TimeString")
    @ResponseWrapper(localName = "time_stringResponse", targetNamespace = "http://ch02.tsa", className = "clienta.TimeStringResponse")
    public String timeString(
        @WebParam(name = "client_message", targetNamespace = "http://ch02.tsa")
        String clientMessage);

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod(operationName = "time_elapsed")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "time_elapsed", targetNamespace = "http://ch02.tsa", className = "clienta.TimeElapsed")
    @ResponseWrapper(localName = "time_elapsedResponse", targetNamespace = "http://ch02.tsa", className = "clienta.TimeElapsedResponse")
    public long timeElapsed();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "acceptInput", targetNamespace = "http://ch02.tsa", className = "clienta.AcceptInput")
    public void acceptInput(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
