
package clienta;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RevisedTimeServer", targetNamespace = "http://ch02.tsa", wsdlLocation = "http://127.0.0.1:9876/tc?wsdl")
public class RevisedTimeServer
    extends Service
{

    public static void main(String[] args) {
        RevisedTimeServer revisedTimeServer = new RevisedTimeServer();
        AnnotatedTimeServer annotatedTimeServerPort = revisedTimeServer.getAnnotatedTimeServerPort();

        annotatedTimeServerPort.acceptInput("foo");
    }

    private final static URL REVISEDTIMESERVER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clienta.RevisedTimeServer.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clienta.RevisedTimeServer.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9876/tc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9876/tc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REVISEDTIMESERVER_WSDL_LOCATION = url;
    }

    public RevisedTimeServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevisedTimeServer() {
        super(REVISEDTIMESERVER_WSDL_LOCATION, new QName("http://ch02.tsa", "RevisedTimeServer"));
    }

    /**
     * 
     * @return
     *     returns AnnotatedTimeServer
     */
    @WebEndpoint(name = "AnnotatedTimeServerPort")
    public AnnotatedTimeServer getAnnotatedTimeServerPort() {
        return super.getPort(new QName("http://ch02.tsa", "AnnotatedTimeServerPort"), AnnotatedTimeServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnotatedTimeServer
     */
    @WebEndpoint(name = "AnnotatedTimeServerPort")
    public AnnotatedTimeServer getAnnotatedTimeServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ch02.tsa", "AnnotatedTimeServerPort"), AnnotatedTimeServer.class, features);
    }

}
