
package ch03.image.client;

import java.awt.Image;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SkiImageService", targetNamespace = "http://image.ch03/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SkiImageService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.awt.Image
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://image.ch03/", className = "ch03.image.client.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://image.ch03/", className = "ch03.image.client.GetImageResponse")
    public Image getImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.awt.Image>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImages", targetNamespace = "http://image.ch03/", className = "ch03.image.client.GetImages")
    @ResponseWrapper(localName = "getImagesResponse", targetNamespace = "http://image.ch03/", className = "ch03.image.client.GetImagesResponse")
    public List<Image> getImages();

}
