
package clientTC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TempService", targetNamespace = "http://tempConvertURI.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TempService {


    /**
     * 
     * @param t
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "c2F", targetNamespace = "http://tempConvertURI.org/", className = "clientTC.C2F")
    @ResponseWrapper(localName = "c2FResponse", targetNamespace = "http://tempConvertURI.org/", className = "clientTC.C2FResponse")
    public double c2F(
        @WebParam(name = "t", targetNamespace = "http://tempConvertURI.org/")
        double t);

    /**
     * 
     * @param t
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "f2C", targetNamespace = "http://tempConvertURI.org/", className = "clientTC.F2C")
    @ResponseWrapper(localName = "f2CResponse", targetNamespace = "http://tempConvertURI.org/", className = "clientTC.F2CResponse")
    public double f2C(
        @WebParam(name = "t", targetNamespace = "http://tempConvertURI.org/")
        double t);

}
