
package clientTC;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TempServiceImplService", targetNamespace = "http://tempConvertURI.org/", wsdlLocation = "http://127.0.0.1:9876/tc?wsdl")
public class TempServiceImplService
    extends Service
{


    public static void main(String[] args) {
        TempServiceImplService tempServiceImplService = new TempServiceImplService();

        TempService port = tempServiceImplService.getTempServicePort();
        double d1 = -40.1, d2 = -39.4;
              System.out.printf("f2C(%f) = %f\n", d1, port.f2C(d1));
              System.out.printf("c2F(%f) = %f\n", d2, port.c2F(d2));

    }

    private final static URL TEMPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clientTC.TempServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clientTC.TempServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9876/tc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9876/tc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEMPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TempServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempServiceImplService() {
        super(TEMPSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://tempConvertURI.org/", "TempServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns TempService
     */
    @WebEndpoint(name = "TempServicePort")
    public TempService getTempServicePort() {
        return super.getPort(new QName("http://tempConvertURI.org/", "TempServicePort"), TempService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempService
     */
    @WebEndpoint(name = "TempServicePort")
    public TempService getTempServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempConvertURI.org/", "TempServicePort"), TempService.class, features);
    }

}
