
package ch02.tc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TempService", targetNamespace = "http://tempConvertURI.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TempService {


    /**
     * 
     * @param t
     * @return
     *     returns double
     */
    @WebMethod(operationName = "c2f", action = "http://tempConvertURI.org/c2f")
    @WebResult(name = "c2fResult", targetNamespace = "http://tempConvertURI.org/")
    @RequestWrapper(localName = "c2f", targetNamespace = "http://tempConvertURI.org/", className = "ch02.tc.C2F")
    @ResponseWrapper(localName = "c2fResponse", targetNamespace = "http://tempConvertURI.org/", className = "ch02.tc.C2FResponse")
    public double c2F(
        @WebParam(name = "t", targetNamespace = "http://tempConvertURI.org/")
        double t);

    /**
     * 
     * @param t
     * @return
     *     returns double
     */
    @WebMethod(operationName = "f2c", action = "http://tempConvertURI.org/f2c")
    @WebResult(name = "f2cResult", targetNamespace = "http://tempConvertURI.org/")
    @RequestWrapper(localName = "f2c", targetNamespace = "http://tempConvertURI.org/", className = "ch02.tc.F2C")
    @ResponseWrapper(localName = "f2cResponse", targetNamespace = "http://tempConvertURI.org/", className = "ch02.tc.F2CResponse")
    public double f2C(
        @WebParam(name = "t", targetNamespace = "http://tempConvertURI.org/")
        double t);

}
